export let Products=[
    {id:"1",
     itemName:"Mobile",
     image:"https://www.w3schools.com",
     Description:"Good Mobile",
     Category:"ele",
     Price:"12345",
     Units:"10",
     Active:"1",
    },
    {id:"1",
     itemName:"Mobile",
     Description:"Good Mobile",
     Category:"ele",
     Price:"12345",
     Units:"10",
     Active:"1",
    },
    {id:"1",
     itemName:"Mobile",
     Description:"Good Mobile",
     Category:"ele",
     Price:"12345",
     Units:"10",
     Active:"1",
    },
    {id:"1",
     itemName:"Mobile",
     Description:"Good Mobile",
     Category:"ele",
     Price:"12345",
     Units:"10",
     Active:"1",
    },
    {id:"1",
     itemName:"Mobile",
     Description:"Good Mobile",
     Category:"ele",
     Price:"12345",
     Units:"10",
     Active:"1",
    },
    {id:"1",
     itemName:"Mobile",
     Description:"Good Mobile",
     Category:"ele",
     Price:"12345",
     Units:"10",
     Active:"1",
    },
    {id:"1",
     itemName:"Mobile",
     Description:"Good Mobile",
     Category:"ele",
     Price:"12345",
     Units:"10",
     Active:"1",
    },
    {id:"1",
     itemName:"Mobile",
     Description:"Good Mobile",
     Category:"ele",
     Price:"12345",
     Units:"10",
     Active:"1",
    },
    {id:"1",
     itemName:"Mobile",
     Description:"Good Mobile",
     Category:"ele",
     Price:"12345",
     Units:"10",
     Active:"1",
    }

];